import { mockData } from './mock-data.js';
import { loadState } from './storage.js';
import { ensureProductionReady } from './demo-data.js?v=20260719a';
import { initDashboard } from './dashboard.js?v=20260719a';
import { initPos } from './pos.js?v=20260719a';
import { initOrders } from './orders.js?v=20260719a';
import { initEvents } from './events.js?v=20260719a';
import { initProducts } from './products.js?v=20260719a';
import { initCostCalculator } from './cost-calculator.js?v=20260719a';
import { initInventory } from './inventory.js?v=20260719a';
import { initFinance } from './finance.js?v=20260719a';
import { initSuppliers } from './suppliers.js?v=20260719a';
import { initCustomers } from './customers.js?v=20260719a';
import { initReports } from './reports.js?v=20260719a';
import { initSettings } from './settings.js?v=20260716d';
import { initCalendar } from './calendar.js?v=20260719a';
import { initializeGlobalQA, runIntegrationSnapshot } from './qa-service.js';
import { initPWA } from './pwa.js?v=20260719a';
import { initScanner } from './scanner.js';
import { initQRService } from './qr-service.js';
import { initQRPayment } from './qr-payment.js';
import { initReceiptPrinter } from './receipt-printer.js';
import { initProductionAuth } from './production-auth.js?v=20260716d';
import { startBackendSyncBridge } from './backend-sync.js?v=20260713g';

initializeGlobalQA();
ensureProductionReady();
startBackendSyncBridge();
initProductionAuth();
initPWA();
initScanner();
initQRService();
initQRPayment();
initReceiptPrinter();
const state = loadState(mockData);
initDashboard(state);
initPos();
initOrders();
initEvents();
initProducts();
initCostCalculator();
initInventory();
initFinance();
initSuppliers();
initCustomers();
initReports();
initSettings();
initCalendar();

console.info('[Budsarin QA]', runIntegrationSnapshot());
